### PR TITLE
Fix updating notes, not only database.

### PR DESCRIPTION
**Pull request by shinnkondo**
Thanks for writing a great script!

It seemed like the updating portion of the software did not work as described. 
More precisely, it only updated database, not notes in Evernote.

So I added a line to fix it. I guess this was your original intention.

### CODE REVIEW

**Comment by mdp** [comment]
This looks great. Let me take a look at it more thoroughly tonight and I'll merge it in.

**Comment by shinnkondo** [comment]
Actually, I was not intending to send pull request for changes other than the first commit.
(Because they reflect my preference rather than fix or improvement.)

Sorry that I have not gotten used to this process.
Let me figure out how I can fix my request.

**Comment by shinnkondo** [comment]
I created a new pull request which only contains the fix. See #4 .
(I did not realize that committing after making pull-request would alter the request.)

Again, sorry for confusion and leaving a wasting request in your page.

**Comment by mdp** [comment]
Thanks, I merged in your DB fix. Feel free to do another pull request if you get syntax highlighting working, I'd love to have that in the project.

**Comment by shinnkondo** [comment]
I would love to, but I have some concerns about its dependency to python (and changes to code I would make).
Please see #5 for detail.

**Pull request closed without merging**
