### PR TITLE
Dockerize GistEvernote

### PR DESCRIPTION
**Pull request by mdp**
@cpswan This is my first stab at it. Would be great to get your opinion on it, thanks.

### CODE REVIEW

**Comment by cpswan** [comment]
The key thing to successfully putting it into Docker will be having a clean way to pass the security tokens into the config file (and any other parameters). There are a bunch of ways to do this, but the three options I'd explore are:

1) Bind mount the config.yml from the host
2) Pass the parameters in as env variables
3) Have a configure script that reads in the tokens etc.

I'd probably go with 3 as it keeps all the state in the container, but that's just a personal preference. You've gone with 1, which is perfectly acceptable.

Even without considering Docker I think the project would benefit from having a scripted way to put the tokens etc. into the config (or at the very least have text placeholders that can easily be replaced with sed - at the moment the combination of an actual token and repeats of things like `username` makes this hard).

## Other things

It's best practice not to run stuff in containers as root, so I'd create a user and then run stuff as that user.

```
# add an evergist user 
RUN useradd -m evergist
USER evergist
```

I also generally use the git download rather than installing git then using git clone

```
# put unzip and wget into apt-get install rather than git
wget https://github.com/mdp/GistEvernoteImport/archive/master.zip
unzip master.zip
# this probably changes the app directory thing you were doing
```

**Comment by mdp** [comment]
Thanks Chris, I'm fairly new to Docker, so this is a really helpful writeup. I'll integrate some of your proposed changes tomorrow (non-priv user and zip instead of git) when I've got some spare time.

I chose the mount because it also needs to save out the sqlite database (data/db.sql) to someplace outside the container, but I agree that it would be ideal to have a config script for reading the tokens.

**Comment by mdp** [comment]
@cpswan OK, this is live on Docker hub as an automated build - https://registry.hub.docker.com/u/mpercival/gistevernote/dockerfile/ 

I've implemented the following
- Non-root user
- Pull from archive.zip rather than git
- Added a setup.rb script for building the config.yml

Thanks for your help on this. I'm much happier having this running in a docker container.

**Comment by cpswan** [comment]
I've done a PR with some tidy up of the Dockerfile.

The next thing needed is some documentation on Docker Hub. This could be the same README file as you have for the whole project (if you rename it to .md), or it could be a new file (in a new git repo) just for Docker. I also generally add an example command line as a comment at the end of the Dockerfile.

The Docker Hub page also needs a description to be added, as this isn't sourced from README.md.

Some dire warnings about running it from multiple places (== multiple containers) to avoid dupes might also be needed (or at least point out the the issue can be resolved by deleting the contents of the notebook and the db.sql file and rerunning - the good news here is that Gist is always the single source of truth, and so the Evernote part can be deleted without consequence).

**Pull request merged**
